Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  Pee-Dom - Android Studio Prebuild" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# 1. Verify repo root
if (-not (Test-Path "package.json")) {
    Write-Host "ERROR: Run this script from the repo root (where package.json lives)." -ForegroundColor Red
    exit 1
}

# 2. Check Node
$nodeVer = node --version 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Node.js not found. Install from https://nodejs.org" -ForegroundColor Red
    exit 1
}
Write-Host "  Node: $nodeVer" -ForegroundColor Green

# 3. Check Expo CLI
$expoVer = npx expo --version 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Expo CLI not accessible. Run: npm install" -ForegroundColor Red
    exit 1
}
Write-Host "  Expo CLI: $expoVer" -ForegroundColor Green

# 4. Find Android SDK
$sdkPath = $env:ANDROID_HOME
if (-not $sdkPath) {
    $sdkPath = $env:ANDROID_SDK_ROOT
}
if (-not $sdkPath) {
    $c1 = "$env:LOCALAPPDATA\Android\Sdk"
    $c2 = "$env:USERPROFILE\AppData\Local\Android\Sdk"
    if (Test-Path $c1) {
        $sdkPath = $c1
    } elseif (Test-Path $c2) {
        $sdkPath = $c2
    }
}
if (-not $sdkPath -or -not (Test-Path $sdkPath)) {
    Write-Host ""
    Write-Host "ERROR: Android SDK not found." -ForegroundColor Red
    Write-Host "  Install Android Studio: https://developer.android.com/studio" -ForegroundColor Yellow
    Write-Host "  Then set the ANDROID_HOME environment variable." -ForegroundColor Yellow
    exit 1
}
Write-Host "  Android SDK: $sdkPath" -ForegroundColor Green

# 5. Check Java
$javaOut = java -version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "  Java: found" -ForegroundColor Green
} else {
    Write-Host "  Java: not in PATH (Android Studio bundled JDK will be used)" -ForegroundColor Yellow
}

Write-Host ""

# 6. Load .env.local
Write-Host "Loading .env.local..." -ForegroundColor Yellow
if (-not (Test-Path ".env.local")) {
    Write-Host "  WARNING: .env.local not found." -ForegroundColor Yellow
} else {
    $envLines = Get-Content ".env.local"
    foreach ($envLine in $envLines) {
        $envLine = $envLine.Trim()
        if ($envLine -and -not $envLine.StartsWith("#")) {
            $parts = $envLine -split "=", 2
            if ($parts.Length -eq 2) {
                $k = $parts[0].Trim()
                $v = $parts[1].Trim()
                $v = $v -replace '^"(.*)"$', '$1'
                $v = $v -replace "^'(.*)'$", '$1'
                [System.Environment]::SetEnvironmentVariable($k, $v, "Process")
                Write-Host "  Set $k" -ForegroundColor DarkGray
            }
        }
    }
    Write-Host "  .env.local loaded" -ForegroundColor Green
}

$env:ANDROID_HOME = $sdkPath
$env:ANDROID_SDK_ROOT = $sdkPath
Write-Host ""

# 7. npm install
Write-Host "Running npm install..." -ForegroundColor Yellow
npm install
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: npm install failed." -ForegroundColor Red
    exit 1
}
Write-Host "  npm install complete" -ForegroundColor Green
Write-Host ""

# 8. expo prebuild
Write-Host "Running expo prebuild --platform android --clean..." -ForegroundColor Yellow
Write-Host ""
npx expo prebuild --platform android --clean
if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "ERROR: expo prebuild failed." -ForegroundColor Red
    Write-Host "Common fixes:" -ForegroundColor Yellow
    Write-Host "  - Missing assets: run  node generate-placeholder-assets.js" -ForegroundColor Yellow
    Write-Host "  - Wrong env key: rename EXPO_PUBLIC_SUPABASE_KEY to EXPO_PUBLIC_SUPABASE_ANON_KEY in .env.local" -ForegroundColor Yellow
    Write-Host "  - Plugin error: check @sentry/react-native/expo config in app.config.ts" -ForegroundColor Yellow
    exit 1
}
Write-Host ""
Write-Host "  expo prebuild complete" -ForegroundColor Green
Write-Host ""

# 9. Write android/local.properties
Write-Host "Writing android/local.properties..." -ForegroundColor Yellow
$sdkFwd = $sdkPath -replace "\\", "/"
$lpContent = "## Generated by prebuild.ps1 - do not commit`nsdk.dir=$sdkFwd"
$mapsKey = $env:ANDROID_GOOGLE_MAPS_API_KEY
if ($mapsKey) {
    $lpContent += "`nANDROID_GOOGLE_MAPS_API_KEY=$mapsKey"
    Write-Host "  Google Maps key included" -ForegroundColor Green
} else {
    Write-Host "  ANDROID_GOOGLE_MAPS_API_KEY not set (add to .env.local for map support)" -ForegroundColor Yellow
}
Set-Content -Path "android\local.properties" -Value $lpContent -Encoding UTF8
Write-Host "  android/local.properties written" -ForegroundColor Green
Write-Host ""

# 10. Done
Write-Host "============================================================" -ForegroundColor Green
Write-Host "  PREBUILD COMPLETE" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Open Android Studio" -ForegroundColor White
Write-Host "     File > Open > select the android/ subfolder (NOT the repo root)" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  2. Wait for Gradle sync (5-10 min first run)" -ForegroundColor White
Write-Host ""
Write-Host "  3. Start Metro in a separate terminal:" -ForegroundColor White
Write-Host "     npx expo start --dev-client" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  4. In Android Studio: Run > Run 'app'" -ForegroundColor White
Write-Host ""
